# Generated by Django 2.1.2 on 2018-10-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ra', models.PositiveIntegerField(default=123456)),
                ('trancou', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
